#!/bin/bash
yum install iptables-services -y

sudo cat > /root/iptables<<EOF
# Generated by iptables-save v1.4.21 on Fri Feb  3 09:45:25 2017
# opstools server ip 192.168.1.50
# enp0s3 --> net device (eth0)
# iptables-restore < this_file
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -i eth0 -j ACCEPT
-A INPUT -i lo -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -d 192.168.1.50/32 -p tcp -m tcp --sport 513:65535 --dport 2222 -m state --state NEW,ESTABLISHED -j ACCEPT
-A INPUT -d 192.168.1.50/32 -p tcp -m tcp --sport 513:65535 --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT
-A INPUT -j LOG --log-prefix "INPUT:DROP:" --log-level 6
-A INPUT -j DROP
-A OUTPUT -s 192.168.1.50/32 -j ACCEPT
-A OUTPUT -o enp0s3 -j ACCEPT
-A OUTPUT -o eth0 -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -s 192.168.1.50/32 -p tcp -m tcp --sport 22 --dport 513:65535 -m state --state ESTABLISHED -j ACCEPT
-A OUTPUT -j LOG --log-prefix "OUTPUT:DROP:" --log-level 6
-A OUTPUT -j DROP
COMMIT
# Completed on Fri Feb  3 09:45:25 2017
EOF

echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjoaPwjFHZuaR085o6DWOQcNFUXHnWZd3I6MO4uLb+hGRJur75E7K3zy7uZwSeaOD2SEFynsIQWyystdU7nySSgHnGCnEXFX4C3UNsbRJayJ1na4ING/FgEJaa7rXCB55rgUBFrrmQCl0+GPjDctFZTmP8cH0QLsIqXeFzrvZoRWYlpaiPtSGjcwJ9N8cVODJBtRJExZZCmudiVyNvyX0V6fQSpZCr7PEHIxZB50IBaDwvYex9L6GfKglM6V4QuGbvpJq2l0ms9AKkCMRgiOlYJUcj8SRYf4s812CeClIf1aJtz6EDuLFvEXSuL13GNZbhaas9gTTJKOKB3Nj0noVF jbadiapa@skyblue" >> .ssh/authorized_keys
echo "ssh-dss AAAAB3NzaC1kc3MAAACBALgi6eI/S91pCR1fWgiGq8EcBI/SSocTc48WqIqIPlEYvSnuhOFFeOxoOVBhfcxV8vxQwHMCNmJVk4nCdUfg6K0U9ehymKN7fF6NM/+RMkJJ/FRBb+fRW8dgn3v74AwC6+3IVgYZT/8ZIalIwWhPupeiYONcmn3nVo4bGICwJ66lAAAAFQDzpXrA3zA/cqErJnnGFTMXpQOamwAAAIBci9E46kX5op4whbubLwGbfUydsNBsoTYWGh0EduiUeJzC0kVYdUrLndGZ761MLXFXo5fzK920kmpPcbTrGUuQysB4qRIs6bNtqfD9lgxqA/6nvYIW5oHUH0cnzjQg2AMXSqavGzbqw3AS0wxD4JEV9rVtq9ZhCaHQ1/GmF/+pyQAAAIBfrxJfiEQI50lonY/q9HVuGu/IIgqP5MDGcdDJVUsXe8XkwymWn2ZSqseci9joUSXUDU7SNIVYiws0skUARzXqKPcy2lPPe8yORG9c5ZV5YnOvEUZ+B8M+dbWIZQ5UT2xSkwWRMkaXkrs+bJESr76Dvum+xs3Y89WKD3Ms9lEyDA== jbadiapa@skyblue" >> .ssh/authorized_keys

sudo mkdir /root/.ssh
sudo cat > /root/.ssh/authorized_keys<<EOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjoaPwjFHZuaR085o6DWOQcNFUXHnWZd3I6MO4uLb+hGRJur75E7K3zy7uZwSeaOD2SEFynsIQWyystdU7nySSgHnGCnEXFX4C3UNsbRJayJ1na4ING/FgEJaa7rXCB55rgUBFrrmQCl0+GPjDctFZTmP8cH0QLsIqXeFzrvZoRWYlpaiPtSGjcwJ9N8cVODJBtRJExZZCmudiVyNvyX0V6fQSpZCr7PEHIxZB50IBaDwvYex9L6GfKglM6V4QuGbvpJq2l0ms9AKkCMRgiOlYJUcj8SRYf4s812CeClIf1aJtz6EDuLFvEXSuL13GNZbhaas9gTTJKOKB3Nj0noVF jbadiapa@skyblue
ssh-dss AAAAB3NzaC1kc3MAAACBALgi6eI/S91pCR1fWgiGq8EcBI/SSocTc48WqIqIPlEYvSnuhOFFeOxoOVBhfcxV8vxQwHMCNmJVk4nCdUfg6K0U9ehymKN7fF6NM/+RMkJJ/FRBb+fRW8dgn3v74AwC6+3IVgYZT/8ZIalIwWhPupeiYONcmn3nVo4bGICwJ66lAAAAFQDzpXrA3zA/cqErJnnGFTMXpQOamwAAAIBci9E46kX5op4whbubLwGbfUydsNBsoTYWGh0EduiUeJzC0kVYdUrLndGZ761MLXFXo5fzK920kmpPcbTrGUuQysB4qRIs6bNtqfD9lgxqA/6nvYIW5oHUH0cnzjQg2AMXSqavGzbqw3AS0wxD4JEV9rVtq9ZhCaHQ1/GmF/+pyQAAAIBfrxJfiEQI50lonY/q9HVuGu/IIgqP5MDGcdDJVUsXe8XkwymWn2ZSqseci9joUSXUDU7SNIVYiws0skUARzXqKPcy2lPPe8yORG9c5ZV5YnOvEUZ+B8M+dbWIZQ5UT2xSkwWRMkaXkrs+bJESr76Dvum+xs3Y89WKD3Ms9lEyDA== jbadiapa@skyblue
EOF

systemctl enable iptables
iptables-restore < /root/iptables
systemctl start iptables
iptables-restore < /root/iptables

